version: '3.7'

services:
    proxy:
        image: ghcr.io/k0in/docker-wireguard-socks-proxy:latest
        restart: always
        ports:
            - "1080:1080"
        volumes:
            - ./:/etc/wireguard/:ro # path to your config
        cap_add:
            - NET_ADMIN

# if you get errors when trying to connect to a https host uncomment the following line
#        networks:
#            - wireguard_driver

# networks:
#     wireguard_driver:
#         driver: bridge
#         driver_opts:
#             com.docker.network.driver.mtu: 1450